function comparisonplot(x1, ymatrix1, figureTitle, xTitle, yTitle, labelNames, note, filename)
%
% $Id: comparisonplot.m 5 2008-11-18 04:11:57Z bjandre $
%
% Copyright 2007, 2008 Benjamin Andre
%
% This file is part of odeparams.
%
% odeparams is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%  
% Odeparams is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
%  
% You should have received a copy of the GNU General Public License
% along with odeparams.  If not, see <http://www.gnu.org/licenses/>.
%

%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
 
%  Auto-generated by MATLAB on 25-Jun-2007 12:48:30
 
% Create figure
figure1 = figure;
 
% Create axes
axes1 = axes('Parent',figure1);
box('on');
hold('all');
 
% Create multiple lines using matrix input to plot
plot1 = plot(x1,ymatrix1);
markers = ['*'; '+'; '.'; 'x'; 'o'];
[nx, ny] = size(ymatrix1);
for i=1:(ny/2)
    set(plot1(2*i-1),'Marker',markers(i));
end 
% Create title
title(figureTitle);
 
% Create xlabel
xlabel(xTitle);
 
% Create ylabel
ylabel(yTitle);
 
% Create legend
legend1 = legend(axes1,labelNames);
 
% Create textbox
annotation1 = annotation(...
  figure1,'textbox',...
  'Position',[0.2232 0.7619 0.2982 0.07619],...
  'FitHeightToText','off',...
  'EdgeColor','none',...
  'LineStyle','none',...
  'String',{note});

print(figure1, '-dpdf', filename);
